import type { Metadata } from "next";
import "./scss/style.scss";
import localFont from 'next/font/local'
import HeaderComponent from "./ui/HeaderComponent";
import Cart from "./ui/Cart";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const GTEestiProText = localFont({
  src: [
    {
      path: './fonts/EestiBold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/EestiRegular.woff2',
      weight: '500',
      style: 'normal',
    },
  ]
})


export default function RootLayout({ children, }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={GTEestiProText.className}>
        <HeaderComponent />
        <main>
          {children}
        </main>
        <Cart />
      </body>
    </html>
  );
}
