import type { Metadata } from "next";
import "./scss/style.scss";
import localFont from 'next/font/local'
import Header from "./ui/header";
import Cart from "./ui/Cart";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const GTEestiProText = localFont({
  src: [
    {
      path: './fonts/EestiBold.OTF',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/EestiRegular.OTF',
      weight: '500',
      style: 'normal',
    },
  ]
})


export default function RootLayout({ children, }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <Header />
      <body className={GTEestiProText.className}>
        <main>
        {children}
        </main>
      </body>
      <Cart />
    </html>
  );
}
